{
 "title": "Home",
 "time": { "from": "$CTF_START_DATE", "to": "2030-01-01T12:00:00.000Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "CTF_START_DATE", "label": "Start date", "query": "$CTF_START_DATE" },
   { "name": "CTF_TICK_LENGTH", "label": "Tick length", "query": "$CTF_TICK_LENGTH" },
   { "name": "CTF_SHOVEL_URL", "label": "Shovel host", "query": "$CTF_SHOVEL_URL" },
   { "name": "CTF_SERVICES", "label": "Services", "query": "$CTF_SERVICES" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flows per tick",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flows,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "rawQueryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flows,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "FLAG IN/OUT per tick",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flag_out,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG OUT\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "rawQueryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flag_out,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG OUT\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    COUNT(*) as flag_in\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG IN\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "rawQueryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    COUNT(*) as flag_in\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG IN\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Last flags IN/OUT",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    ts_start / 1000000 AS time,\n    concat('tick=', (ts_start - ctf_start_ts) / tick_length, ' ', metadata->>'$.flowvars[0].match') AS text\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND metadata->>'$.flowvars[0].match' IS NOT NULL\nORDER BY ts_start DESC\nLIMIT 1000",
     "rawQueryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    ts_start / 1000000 AS time,\n    concat('tick=', (ts_start - ctf_start_ts) / tick_length, ' ', metadata->>'$.flowvars[0].match') AS text\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND metadata->>'$.flowvars[0].match' IS NOT NULL\nORDER BY ts_start DESC\nLIMIT 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "${CTF_SERVICES}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "CTF_SERVICES" },
  {
   "title": "Flows per tick for ${CTF_SERVICES}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flows,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND (CONCAT(src_ip, ':', src_port) == \"${CTF_SERVICES:value}\" OR CONCAT(dest_ip, ':', dest_port) == \"${CTF_SERVICES:value}\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "rawQueryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flows,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND (CONCAT(src_ip, ':', src_port) == \"${CTF_SERVICES:value}\" OR CONCAT(dest_ip, ':', dest_port) == \"${CTF_SERVICES:value}\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "FLAG IN/OUT per tick for ${CTF_SERVICES}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flag_out,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG OUT\")\n    AND (CONCAT(src_ip, ':', src_port) == \"${CTF_SERVICES:value}\" OR CONCAT(dest_ip, ':', dest_port) == \"${CTF_SERVICES:value}\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "rawQueryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    (ts_start - ctf_start_ts) / tick_length as tick,\n    COUNT(*) as flag_out,\n    (ctf_start_ts + cast((ts_start - ctf_start_ts) / tick_length + 1 as int) * tick_length) as ts_to_url\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG OUT\")\n    AND (CONCAT(src_ip, ':', src_port) == \"${CTF_SERVICES:value}\" OR CONCAT(dest_ip, ':', dest_port) == \"${CTF_SERVICES:value}\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    COUNT(*) as flag_in\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG IN\")\n    AND (CONCAT(src_ip, ':', src_port) == \"${CTF_SERVICES:value}\" OR CONCAT(dest_ip, ':', dest_port) == \"${CTF_SERVICES:value}\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "rawQueryText": "WITH config AS (SELECT \n    (1000000 * UNIXEPOCH(\"${CTF_START_DATE}\")) AS ctf_start_ts,\n    (1000000 * ${CTF_TICK_LENGTH}) AS tick_length\n)\nSELECT\n    (ctf_start_ts + cast(((ts_start - ctf_start_ts) / tick_length) as int) * tick_length) / 1000000 AS time,\n    COUNT(*) as flag_in\nFROM flow, config\nWHERE\n    ts_start / 1000 >= $__from and ts_start / 1000 < $__to\n    AND id IN (SELECT flow_id FROM alert WHERE tag = \"FLAG IN\")\n    AND (CONCAT(src_ip, ':', src_port) == \"${CTF_SERVICES:value}\" OR CONCAT(dest_ip, ':', dest_port) == \"${CTF_SERVICES:value}\")\nGROUP BY cast(((ts_start - ctf_start_ts) / 1000000 / ${CTF_TICK_LENGTH}) as int) * ${CTF_TICK_LENGTH}\n",
     "timeColumns": [ "time" ]
    }
   ]
  }
 ]
}